export enum responseCodeEnums {
  SUCCESS = 200,
  BAD_REQUEST = 400,
  UN_AUTHORIZED,
  FORBIDDEN = 403,
  NOT_FOUND,
  NOT_ALLOWED,
  NOT_ACCEPTABLE,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500,
  SERVER_UNAVAILABLE = 503,
}
